### ISSUE TITLE
Error while running scannet [OOM happens]

### ISSUE THREAD

**Issue by OmarAhmadien** [charlesq34/pointnet2#80]
I downloaded the preprocessed data and tried to run train.py
I get this error:

_

> Limit:                  7901626368
> InUse:                  7888998912
> MaxInUse:               7889023744
> NumAllocs:                     729
> MaxAllocSize:            428098048
> 
> 2018-10-12 10:18:38.952118: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ****************************************************************************************************
> 2018-10-12 10:18:38.952135: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:398 : Resource exhausted: OOM when allocating tensor with shape[32,64,256,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> Traceback (most recent call last):
>   File "train1.py", line 435, in <module>
>     train()
>   File "train1.py", line 168, in train
>     train_one_epoch(sess, ops, train_writer)
>   File "train1.py", line 239, in train_one_epoch
>     ops['train_op'], ops['loss'], ops['pred']], feed_dict=feed_dict)
>   File "/root/miniconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
>     run_metadata_ptr)
>   File "/root/miniconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/root/miniconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
>     run_metadata)
>   File "/root/miniconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,1024,32,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
>          [[{{node gradients/layer1/maxpool_grad/Cast-0-0-TransposeNCHWToNHWC-LayoutOptimizer}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/layer1/maxpool_grad/Cast, PermConstNCHWToNHWC-LayoutOptimizer)]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
>          [[{{node gradients/fa_layer2/conv_0/bn/cond/Merge_grad/cond_grad/_568}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3289_gradients/fa_layer2/conv_0/bn/cond/Merge_grad/cond_grad", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

_

How can I fix that?
Shall I change the batch size to be small?

**Comment by Bierfass** [comment]
Monitor your GPU Memory and lower the batch size. For me a batchsize of 20 works without a memory warning with 12GB of vram

**Comment by OmarAhmadien** [comment]
I actually lowered the batch size to be 10 and it worked fine too. Thanks!
